language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - gcc
      - libblas-dev
      - liblapack-dev
      - libatlas-dev
      - gfortran
      - python-numpy
      - python-scipy
      - python-sklearn
install:
  - pip install --upgrade pip
script:
  - python setup.py test
