
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-12-18T15:47:43+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f6983504c7f3e648c4378a22d9ef72148c5c32f",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
