
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "319e6730c2dbc1791012c7c2ab8fc62baf479b1b",
 "version": "1.2.107"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
