language: python
python: 3.5
env:
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django18
  - TOX_ENV=py35-django19
  - TOX_ENV=coverage
# command to install dependencies
install:
  - pip install tox coverage coveralls
# command to run tests
script:
  - tox -e $TOX_ENV
after_success:
  - bash ditto/scripts/coveralls.sh
# containers
sudo: false
