# lextab.py. This file automatically created by PLY (version 3.8). Don't edit!
_tabversion   = '3.8'
_lextokens    = set(['USEREMAIL', 'PEPMASS', 'FORMAT', 'DECOY', 'DB', 'EQUAL', 'CHAR', 'FRAMES', 'ITOL', 'TOL', 'REPORT', 'QUANTITATION', 'COM', 'CHARGE_VALUE', 'COMMENT', 'SEARCH', 'MODS', 'REPTYPE', 'TITLE', 'TOLU', 'SEG', 'TAG', 'MASS', 'MULTI_SITE_MODS', 'TAXONOMY', 'RAWSCANS', 'COMMA', 'USERNAME', 'IONS', 'END', 'PEP_ISOTOPE_ERROR', 'SPACE', 'PRECURSOR', 'CLE', 'BEGIN', 'IT_MODS', 'PFA', 'AUTO', 'SEQ', 'INT', 'FLOAT', 'AND', 'ITOLU', 'LOCUS', 'INSTRUMENT', 'CHARGE', 'ETAG', 'RTINSECONDS', 'RAWFILE', 'ERRORTOLERANT', 'CUTOUT', 'COMP', 'USER'])
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_COMP>COMP)|(?P<t_ETAG>ETAG)|(?P<t_LOCUS>LOCUS)|(?P<t_PEPMASS>PEPMASS)|(?P<t_RAWFILE>RAWFILE)|(?P<t_RAWSCANS>RAWSCANS)|(?P<t_RTINSECONDS>RTINSECONDS)|(?P<t_SEQ>SEQ)|(?P<t_TAG>TAG)|(?P<t_TITLE>TITLE)|(?P<t_CLE>CLE)|(?P<t_COM>COM)|(?P<t_CUTOUT>CUTOUT)|(?P<t_DB>DB)|(?P<t_DECOY>DECOY)|(?P<t_ERRORTOLERANT>ERRORTOLERANT)|(?P<t_FORMAT>FORMAT)|(?P<t_FRAMES>FRAMES)|(?P<t_ITOLU>ITOLU)|(?P<t_ITOL>ITOL)|(?P<t_MASS>MASS)|(?P<t_MODS>MODS)|(?P<t_MULTI_SITE_MODS>MULTI_SITE_MODS)|(?P<t_PEP_ISOTOPE_ERROR>PEP_ISOTOPE_ERROR)|(?P<t_PFA>PFA)|(?P<t_PRECURSOR>PRECURSOR)|(?P<t_QUANTITATION>QUANTITATION)|(?P<t_REPORT>REPORT)|(?P<t_REPTYPE>REPTYPE)|(?P<t_SEARCH>SEARCH)|(?P<t_SEG>SEG)|(?P<t_TAXONOMY>TAXONOMY)|(?P<t_USEREMAIL>USEREMAIL)|(?P<t_USERNAME>USERNAME)|(?P<t_USER>USER)|(?P<t_BEGIN>BEGIN)|(?P<t_END>END)|(?P<t_IONS>IONS)|(?P<t_CHARGE>CHARGE)|(?P<t_INSTRUMENT>INSTRUMENT)|(?P<t_IT_MODS>IT_MODS)|(?P<t_TOLU>TOLU)|(?P<t_TOL>TOL)|(?P<t_EQUAL>=)|(?P<t_COMMA>,)|(?P<t_COMMENT>(\\#){3}.*)|(?P<t_CHARGE_VALUE>[0-9]+(\\+|-))|(?P<t_FLOAT>-{0,1}[0-9]+\\.[0-9]+)|(?P<t_INT>-{0,1}[0-9]+)|(?P<t_AND>and)|(?P<t_AUTO>AUTO)|(?P<t_SPACE>[\\t\\s])|(?P<t_CHAR>[^,=])', [None, ('t_COMP', 'COMP'), ('t_ETAG', 'ETAG'), ('t_LOCUS', 'LOCUS'), ('t_PEPMASS', 'PEPMASS'), ('t_RAWFILE', 'RAWFILE'), ('t_RAWSCANS', 'RAWSCANS'), ('t_RTINSECONDS', 'RTINSECONDS'), ('t_SEQ', 'SEQ'), ('t_TAG', 'TAG'), ('t_TITLE', 'TITLE'), ('t_CLE', 'CLE'), ('t_COM', 'COM'), ('t_CUTOUT', 'CUTOUT'), ('t_DB', 'DB'), ('t_DECOY', 'DECOY'), ('t_ERRORTOLERANT', 'ERRORTOLERANT'), ('t_FORMAT', 'FORMAT'), ('t_FRAMES', 'FRAMES'), ('t_ITOLU', 'ITOLU'), ('t_ITOL', 'ITOL'), ('t_MASS', 'MASS'), ('t_MODS', 'MODS'), ('t_MULTI_SITE_MODS', 'MULTI_SITE_MODS'), ('t_PEP_ISOTOPE_ERROR', 'PEP_ISOTOPE_ERROR'), ('t_PFA', 'PFA'), ('t_PRECURSOR', 'PRECURSOR'), ('t_QUANTITATION', 'QUANTITATION'), ('t_REPORT', 'REPORT'), ('t_REPTYPE', 'REPTYPE'), ('t_SEARCH', 'SEARCH'), ('t_SEG', 'SEG'), ('t_TAXONOMY', 'TAXONOMY'), ('t_USEREMAIL', 'USEREMAIL'), ('t_USERNAME', 'USERNAME'), ('t_USER', 'USER'), ('t_BEGIN', 'BEGIN'), ('t_END', 'END'), ('t_IONS', 'IONS'), ('t_CHARGE', 'CHARGE'), ('t_INSTRUMENT', 'INSTRUMENT'), ('t_IT_MODS', 'IT_MODS'), ('t_TOLU', 'TOLU'), ('t_TOL', 'TOL'), ('t_EQUAL', 'EQUAL'), ('t_COMMA', 'COMMA'), ('t_COMMENT', 'COMMENT'), None, ('t_CHARGE_VALUE', 'CHARGE_VALUE'), None, ('t_FLOAT', 'FLOAT'), ('t_INT', 'INT'), ('t_AND', 'AND'), ('t_AUTO', 'AUTO'), ('t_SPACE', 'SPACE'), ('t_CHAR', 'CHAR')])]}
_lexstateignore = {'INITIAL': '\n\r'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
