
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-01-10T08:34:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e4053eb76e23255e63dcdd40c673b36d8f3eff3",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
