# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_openpay', '0002_auto_20161213_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='openpay_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='benefits',
            field=jsonfield.fields.JSONField(blank=True, verbose_name='Benefits (JSON)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='plan',
            name='excerpt',
            field=models.CharField(blank=True, max_length=250, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='django_openpay.Address', verbose_name='Address'),
        ),
    ]
