sudo: false
language: generic
env:
  global:
    - PKG_NAME="odbo"
    - odbo_CONNECTION_STRING="mysql://root:@127.0.0.1:3306"
install:
  - wget --no-verbose -O anaconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels ostrokach
  - conda config --add channels kimlab
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels omnia
  - conda info -a
  - conda update -q conda
  - conda install -q --yes conda-build anaconda-client git-lfs
  - git lfs pull
  - conda build devtools/conda-recipe/
script:
  - conda create -n _test $PKG_NAME --use-local
  - source activate _test
  - pip install flake8 pytest pytest-runner pytest-cov pytest-logging
  - flake8 .
  - py.test -vvv
  - source deactivate
after_success:
  - echo "Success!"
  - pip install codecov
  - codecov
  - anaconda -t $ANACONDA_TOKEN upload /home/travis/anaconda/conda-bld/linux-64/*.tar.bz2
  - devtools/travis-ci/build-docs.sh
after_failure:
  - echo "Failure!"
after_script:
  - echo "X_X"
