# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('reply_to', models.CharField(max_length=255, verbose_name='reply to')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('postdate', models.DateTimeField(blank=True, null=True, verbose_name='postdate')),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='recipients')),
            ],
            options={
                'verbose_name': 'mass message',
                'ordering': ('-created',),
                'verbose_name_plural': 'mass messages',
            },
        ),
    ]
