# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_massmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_immediately',
            field=models.BooleanField(default=True),
        ),
    ]
