from setuptools import setup

setup(name='pySMS',
        	version= '2.1.9',
    description='ZSMS Python Module',
    author='Ian Doarn',
    author_email='ian.doarn@zimmerbiomet.com',
    url='https://github.com/IanDoarn/pySMS',
    packages=['pySMS',
              'pySMS.npython',
              'pySMS.npython.json',
              'pySMS.utils',
              'pySMS.utils.logic',
              'pySMS.data',
              'pySMS.pgsql',
              'pySMS.pgsql.sql',
              'pySMS.excel',
              'pySMS.excel.ui',
              'pySMS.ui',
              'pySMS.req',
              'pySMS.html',
              'pySMS.html.pathdata',
              'pySMS.html.pathdata.json'],
    package_data={'pySMS.html.pathdata.json': ['*.json'],
                  'pySMS.npython': ['*.exe', '*.pyd', '*.dll', '*.xml'],
                  'pySMS.npython.json': ['*.json'],
                  'pySMS.html': ['*.html'],
                  'pySMS.pgsql.sql': ['*.sql'],
                  'pySMS.data': ['*.json.gz', '*.gz'],
                  'pySMS': ['*.exe', '*.ini']})