site_name: Pynd
site_url: http://d0ugal.github.io/pynd/
site_description: Search Python code.
site_author: Dougal Matthews

theme: material

repo_name: 'GitHub'
repo_url: 'https://github.com/d0ugal/pynd'
copyright: <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>

site_dir: build/docs

markdown_extensions:
    - toc:
       permalink: ¶
    - admonition:
    - codehilite(css_class=code):
    - footnotes:

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'd0ugal'
    twitter: 'd0ugal'
