
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6bc9cb0df8448f488da612184e37d0127fa77c3a",
 "version": "1.2.89"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
