- name: install httpd if needed
  yum:
    name: httpd
    state: present
  when: https_enabled

# TODO: This tends to hang forever and the yum process eventually dies
#- name: upgrade base system
#  yum:
#    name: "*"
#    state: latest

- name: install necessary RPM files
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - python-paramiko
    - nss
    - iptables
    - iptables-services
    - "{{ jenkins_rpm }}"
    - graphviz
    - lftp
    - gcc
    - libffi-devel
    - python-devel
    - openssl-devel
    - libxml2-devel
    - libxslt-devel
    - krb5-workstation
    - python-futures
    - python-six
    - python-unittest2
    - python-configobj
    - python-nose
    - cloud-utils
    - python-glanceclient
    - python-keystoneclient
    - python-novaclient
    - python-neutronclient
    - wget

# This blacklist must be done *after* the package installation defined above,
# otherwise packages can be blacklisted before they are installed initially.
- name: pin certain packages
  lineinfile:
    dest: /etc/yum.conf
    line: "exclude={{ upgrade_blacklist | join(' ') }}"
    state: present
    regexp: "^exclude=.*$"
