sudo: false
language: python
cache: pip

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - BUILD=py
  - BUILD=flake8
  - BUILD=docs

matrix:
  exclude:
    # Sphinx requires python 3.4 or above
    - python: 3.3
      env: BUILD=docs

addons:
  apt:
    packages:
      - language-pack-de

install:
  - pip install tox

script:
  - tox -e $BUILD

deploy:
  provider: pypi
  user: hobarrera
  password:
    secure: LXSgJZMZICS0Xv5qyR/IRgki1Wy23lurmdepsOsjzBM2fv7rgKPlU/MASVCUCmLi9vYYqZu+7ViHeT6uhJXLdwE0NisVYqTg6L4aD1kqDmbjkWFhLKA7DAz1QTAYxrk6TQYmDb+ZbNFZlF21g29nqvqtLwdC4dFnDjXGnupCoeU=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
