language: python
sudo: false
cache:
  directories:
    - eggs
addons:
  apt:
    packages:
      libxml2-dev
      libxslt-dev
      python-imaging
python:
  - 2.6
  - 2.7
env:
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3
  - PLONE=5.0
  - PLONE=5.1
matrix:
  exclude:
    - python: 2.7
      env: PLONE=4.1
    - python: 2.6
      env: PLONE=4.2
    - python: 2.6
      env: PLONE=4.3
    - python: 2.6
      env: PLONE=5.0
    - python: 2.6
      env: PLONE=5.1
before_install:
  - pip install --upgrade pip setuptools
  - if [ $PLONE == 5.0 ]; then pip install --upgrade setuptools==21.0.0; fi
install:
  - python bootstrap$(echo $PLONE | cut -f1 -d.).py -c test-$PLONE.x.cfg
  - bin/buildout -t 5 -Nc test-$PLONE.x.cfg
script:
  - bin/coverage run bin/test
after_success:
  - bin/coveralls
