__version__ = "0.1.3"
__git_commiter_name__ = "Amir Reshef"
__git_commiter_email__ = "amirr@infinidat.com"
__git_branch__ = u'develop'
__git_remote_tracking_branch__ = u'origin/develop'
__git_remote_url__ = u'git@git.infinidat.com:host-opensource/infi.iscsiapi.git'
__git_head_hash__ = 'c23bbd06e2ef61ceb44021a88f6edd933eda1804'
__git_head_subject__ = u'Finished Release v0.1.3'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2016-12-22 16:18:40'
