---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "tacker"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "tacker"

- name: Copying over tacker.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/tacker.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/tacker.conf"
      - "{{ node_custom_config }}/tacker/{{ item }}.conf"
      - "{{ node_custom_config }}/tacker/{{ inventory_hostname }}/tacker.conf"
    dest: "{{ node_config_directory }}/{{ item }}/tacker.conf"
  with_items:
    - "tacker"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ node_custom_config }}/tacker/policy.json"
  register: tacker_policy

- name: Copying over existing policy.json
  template:
    src: "{{ node_custom_config }}/tacker/policy.json"
    dest: "{{ node_config_directory }}/{{ item }}/policy.json"
  with_items:
    - "tacker"
  when:
    tacker_policy.stat.exists
