---
- name: Starting tacker container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ tacker_image_full }}"
    name: "tacker"
    volumes:
      - "{{ node_config_directory }}/tacker/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
