
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2e3698d5ad10e31e85aa9e9b180580a4eef9d6cd",
 "version": "2.10.132"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
