- name: "debug task"
  debug:
    msg: "{{ gcloud_gce_group }}"

- name: "set_job_id"
  set_fact:
    results : "{{ gcloud_gce_group['results'] | first }}"

- name: "include wait"
  include: wait.yml job_obj={{ item }}
  with_items: "{{ results }}"

- name: "Append outputitem"
  set_fact:
    async_outputs_gcloud_gce: "{{ async_outputs_gcloud_gce + [job_result] }}"
  when: state == "present"
