language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - python "$TRAVIS_BUILD_DIR/setup.py" install
  - echo 'yes' | sudo add-apt-repository ppa:ondrej/php
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5.6 php5.6-cli php5.6-xml php5.6-curl php5.6-memcached php5.6-imagick php5.6-dev php-pear php php5.6-mongodb php5.6-mongo
  - sudo update-alternatives --set php /usr/bin/php5.6
  - php -v
  - curl https://getcomposer.org/installer | php
  - chmod +x composer.phar
  - sudo ln -s "$PWD/composer.phar" /usr/local/bin/composer
services:
  - mongodb
script:
  - "$TRAVIS_BUILD_DIR/imboclient/test/travis.sh"

