language: cpp

os: 
  - osx
  - linux 

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
    - PYTHON_EXE=python$TRAVIS_PYTHON_VERSION ./configure

script:
    - "bin/py.test -vvs"

notifications:
    irc:
        channels:
          - "chat.freenode.net#aboutcode"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} : %{build_url}"
