
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4fcfd562479fb7a9a1d24874c68779061905fb5e",
 "version": "0.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
