
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "48d04b2db29a92e3576fedad00fce8e9ae77f6ee",
 "version": "2.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
