---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "horizon"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "horizon"

- name: Copying over horizon.conf
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/horizon/horizon.conf"
  with_first_found:
    - "{{ node_custom_config }}/horizon/{{ inventory_hostname }}/horizon.conf"
    - "{{ node_custom_config }}/horizon/horizon.conf"
    - "horizon.conf.j2"

- name: Copying over local_settings
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/horizon/local_settings"
  with_first_found:
    - "{{ node_custom_config }}/horizon/{{ inventory_hostname }}/local_settings"
    - "{{ node_custom_config }}/horizon/local_settings"
    - "local_settings.j2"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ node_custom_config }}/horizon/{{ item.name }}_policy.json"
  register: custom_policy
  when: item.enabled | bool
  with_items:
    - { name: "ceilometer", enabled: "{{ enable_ceilometer }}" }
    - { name: "cinder", enabled: "{{ enable_cinder }}" }
    - { name: "cloudkitty", enabled: "{{ enable_cloudkitty }}" }
    - { name: "glance", enabled: "{{ enable_glance }}" }
    - { name: "heat", enabled: "{{ enable_heat }}" }
    - { name: "ironic", enabled: "{{ enable_ironic }}" }
    - { name: "keystone", enabled: "{{ enable_keystone }}" }
    - { name: "manila", enabled: "{{ enable_manila }}" }
    - { name: "neutron", enabled: "{{ enable_neutron }}" }
    - { name: "nova", enabled: "{{ enable_nova }}" }
    - { name: "sahara", enabled: "{{ enable_sahara }}" }
    - { name: "senlin", enabled: "{{ enable_senlin }}" }
    - { name: "trove", enabled: "{{ enable_trove }}" }

- name: Copying over existing policy.json
  template:
    src: "{{ node_custom_config }}/horizon/{{ item[0]['name'] }}_policy.json"
    dest: "{{ node_config_directory }}/horizon/{{ item[0]['name'] }}_policy.json"
  when:
    - item[0]['enabled'] | bool
    - item[1]['stat']['exists']
  with_together:
    - [{ name: "ceilometer", enabled: "{{ enable_ceilometer }}" },
       { name: "cinder", enabled: "{{ enable_cinder }}" },
       { name: "cloudkitty", enabled: "{{ enable_cloudkitty }}" },
       { name: "glance", enabled: "{{ enable_glance }}" },
       { name: "heat", enabled: "{{ enable_heat }}" },
       { name: "ironic", enabled: "{{ enable_ironic }}" },
       { name: "keystone", enabled: "{{ enable_keystone }}" },
       { name: "manila", enabled: "{{ enable_manila }}" },
       { name: "neutron", enabled: "{{ enable_neutron }}" },
       { name: "nova", enabled: "{{ enable_nova }}" },
       { name: "sahara", enabled: "{{ enable_sahara }}" },
       { name: "senlin", enabled: "{{ enable_senlin }}" },
       { name: "trove", enabled: "{{ enable_trove }}" }]
    - "{{ custom_policy.results }}"
