sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

python: 3.5

env:
  - TOXENV=py27-pytest27
  - TOXENV=py27-pytest28
  - TOXENV=py27-pytest29
  - TOXENV=py27-pytestmaster
  - TOXENV=py27-pytestfeatures
  - TOXENV=py34-pytest29
  - TOXENV=py35-pytest27
  - TOXENV=py35-pytest28
  - TOXENV=py35-pytest29
  - TOXENV=py35-pytestmaster
  - TOXENV=py35-pytestfeatures

matrix:
  allow_failures:
    - env: TOXENV=py27-pytestfeatures
    - env: TOXENV=py35-pytestfeatures


install:
  - pip install tox

script:
  - tox
