
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-02-07T08:01:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "83e32e6e0ec54a258fec3d0b8bac997af4b0dcea",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
