sudo: false
language: python
python:
- 3.5
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: bideWwWGyNe/GNb8S1Rv4GfjaupvlgTIpuzmHwyyUI5x/RTdBsejIm0Kj76jtE/HLyLQFkcaXgF5fzs8O2SNgBpfN1LSJ5ryJ6hSFxhlMzdhyp9KOZYbrnvbCqCaTG5xju5vKp/O1E8TSUpH0M/e2zgRKTLqwGVNUBCzKknHKSIpsHYNELZM6ubgyDbL/nYRIwaoq/zO8O5i9qjApfBfkvqYZDRvPw/cl2e7a3use686P+14mJMzbvKtQNl3RUkLmAo6chzDdVsXORXU81Kkug2OIvw8InLlVqC+RlcwK9NrFviMkV9VFu6QxHgiGFc9t1qggZ6I9j4zxlGoucNUOaTjxcDdQjtu2Quu3xkDWI6k5da9+J3lNd9SCca7gRUoD5Qxro6yM1qDrPHyyyBwp6dgIbCFcJogpecD4htnOqcntoZ+tZG3CXWDkMeeHeS0whJ2qFDt3wPLFvQtAl289ow7t/fgCv5lp40LJt0WutH7kkL5ssKqfd7pCAEihq3+S21xMReD9l8ADJnqsFT1FbloqUvs/5mw9oPtjCDKDCpIHYNhRBlDZpG7DHzq2zrt+Vh1SL/ZJICrXAJYmbH6MlT3wTggq1kOax8l/GGhvWiyaIRjXaWOVxoJq8kuVZlM6Yz38GIqd/ZYkXKPa/VOIPjE1EYS3twVojbNxt+YklM=
