
LABEL_MULTISIGNAL = 'Multisignal'
LABEL_1SIG_KNOWN = '1Signal-Known'
LABEL_1SIG_CONNECTED = '1Signal-Connected'


DRIVER_LABELS = [LABEL_MULTISIGNAL, LABEL_1SIG_KNOWN, LABEL_1SIG_CONNECTED]

LABEL_POOL_DRIVER_SUFFIX = '-InPool'
POOL_DRIVER_LABELS = [l + LABEL_POOL_DRIVER_SUFFIX for l in DRIVER_LABELS]

DRIVER_LABEL_RANKING = DRIVER_LABELS + POOL_DRIVER_LABELS