
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-01-18T10:05:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "01eafac9e984a8ca4e616b45e01b4d98a8284b54",
 "version": "1.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
