package:
 name: sherpa
 version: '4.8.2' 

build:
 number: 0

 entry_points:
  - sherpa_test = sherpa:clitest
  - sherpa_smoke = sherpa:smoke

requirements:
 build:
  - python x.x
  - numpy 1.9.*
  - setuptools
  - libgcc 4.8.5 # [linux]

 run:
  - python x.x
  - numpy >1.9
  - setuptools
  - pytest
  - libgcc 4.8.5 # [linux]
  - six

about:
 home: http://cxc.cfa.harvard.edu/sherpa/
 summary: Sherpa is the CIAO modeling and fitting application. It enables the user to construct complex models from simple definitions and fit those models to data, using a variety of statistics and optimization methods
 license: GPLv3

