__version__ = "0.3.13"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.3.13)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'eb6f576dcff5f04e44815eebee18b37a1b1680ef'
__git_head_subject__ = 'Finished Release v0.3.13'
__git_head_message__ = ''
__git_dirty_diff__ = ''