
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "52e3cebfa78f306ebf55353f5cdc2aa645834fc6",
 "version": "2.10.129"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
