# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=64, verbose_name='\u8c03\u7528\u65b9\u6cd5')),
                ('query', models.TextField(default='', verbose_name='\u8bf7\u6c42\u53c2\u6570')),
                ('code', models.PositiveIntegerField(verbose_name='\u8bf7\u6c42\u72b6\u6001')),
                ('url', models.CharField(max_length=512, verbose_name='\u8bf7\u6c42\u5730\u5740')),
                ('sql', models.TextField(verbose_name='\u6267\u884csql')),
                ('load_time', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='\u8bf7\u6c42\u65f6\u95f4')),
                ('sql_time', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='sql\u8017\u65f6')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django_nox_loadtimelog',
            },
        ),
    ]
