# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20161120_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='show image'),
        ),
    ]
