limits:
    download: 0
    upload: 0
players:
    default: vlc
save_path: /tmp/touchandgo/
strategy:
    always_sequential: No
    piece_st: 4
    last_piece_st: 2
    chunks_strat: 10
defrag: false
force_ts_proxy_port: true
ts_proxy_port: 8001
