(u"AA", u"Stud Book Français du Cheval Anglo-Arabe"),
(u"AAFE", u"Asociacion Argentina de Fomento Equino"),
(u"ABPSL", u"Associação Brasileira dos Criadores do Cavalo Puro Sangue Lusitano"),
(u"AES", u"Anglo European Studbook"),
(u"AHHA", u"American Holsteiner Horse Association"),
(u"AHS", u"The American Hanovarian Society"),
(u"ANAA", u"Stud-book Français du cheval Anglo-Arabe"),
(u"AWHA", u"Australian Warmblood Horse Association"),
(u"AWÖ", u"Arbeitsgemeinschaft für Warmblutzucht in Österreich"),
(u"AWR", u"American Warmblood Registry"),
(u"AWS", u"American Warmblood Society"),
(u"BAD-WÜ", u"Pferdezuchtverband Baden-Württemberg e.V."),
(u"BAVAR", u"Landesverband Bayerischer Pferdezüchtere V."),
(u"BH", u"Associação Brasileira de Criadores do Cavalo de Hipismo"),
(u"BHHS", u"The British Hanoverian Horse Society"),
(u"BRAND", u"Pferdezuchtverband Brandenburg-Anhalt"),
(u"Bri. WS", u"British Warmblood Society"),
(u"BSHA", u"Bulgarian Sport Horse Association"),
(u"BWBS", u"Warmblood Breeders Studbook – UK"),
(u"BWP", u"Belgisch Warmbloedpaard v.z.w."),
(u"CABSH", u"Croatian Association of Breeders of Sport Horses"),
(u"CCDM", u"Criadores de Caballos Deportivos Mexiacanos"),
(u"CDE", u"Caballo de Deporte Espanol"),
(u"CH", u"Zuchtverband CH-Sportpferde ZVCH Swiss Warmblood"),
(u"Cheval Suisse", u"Studbook Cheval Suisse"),
(u"CSHA", u"Canadian Sport Horse Association"),
(u"CWHBA", u"Canadian Warmblood Horse Breeders Association"),
(u"CZEWB", u"Czech Warmblood Breeders Association"),
(u"DSP", u"Deutsches Sportpferd"),
(u"DWB", u"Danish Warmblood Society"),
(u"EBHA", u"East Bulgarian Horse Association"),
(u"ESHB", u"Estonian Sport Horse Breeders Society"),
(u"FWB", u"Finnish Warmblood"),
(u"GHH", u"Graenseegnens Holstener Hesteavlsforening"),
(u"HAA", u"The Holsteiner Association of Australia"),
(u"HANN", u"Hannoveraner Verband e. V."),
(u"HESS", u"Verband Hessischer Pferdezüchter e.V."),
(u"HHSA", u"Hanoverian Horse Society of Australia"),
(u"HOLST", u"Verband der Züchter des Holsteiner Pferdes e.V."),
(u"HSH", u"Hungarian Sporthorse studbook"),
(u"ISH", u"Irish Sport Horse Studbook"),
(u"ISREG", u"International Sporthorse Registry Oldenburg Registry North America"),
(u"ISSA", u"International Sporthorse Studbook Australia"),
(u"KISB / GIDR", u"Kisberi and Gidran Horse Breeders Association"),
(u"KWPN", u"Koninklijk Warmbloed Paardenstamboek Nederland"),
(u"KWPN NA", u"KWPN of North America, Inc."),
(u"LBHA", u"Latvian Horse Breeding Association"),
(u"LHBAT", u"Latvian Horse Breeders Association"),
(u"LUSIT", u"Associação Portuguesa De Criadores do Cavalo Puro Sangue Lusitano"),
(u"MECKL", u"Verband der Pferdezüchter Mecklenburg-Vorpommern e.V."),
(u"MIPAAF", u"Italian Horse Department"),
(u"NRPS", u"Nederlands Rijpaarden en Pony Stamboek"),
(u"NWB", u"Norwegian Warmblood Association"),
(u"OLDBG", u"Verband der Züchter des Oldenburger Pferdes e.V."),
(u"OS", u"Springpferdezuchtverband Oldenburg-International e.V"),
(u"P.R.E.", u"Asociacion Nacional De Criadores De Caballos de Pura Raza Española"),
(u"PSH", u"Portuguese Sport Horse"),
(u"PZHK", u"Polish Horse Breeders Association"),
(u"RHEIN", u"Rheinisches Pferdestammbuch e.V."),
(u"SA", u"Pferdezuchtverband Sachsen Anhalt e.v."),
(u"SACHS", u"Pferdezuchtverband Sachsen e.V."),
(u"SATHU", u"Pferdezuchtverband Sachsen-Thüringen e.V"),
(u"SAWHS", u"South African Warmblood Society"),
(u"SBS", u"Stud-book sBs, le cheval de Sport Belge"),
(u"SCSL", u"Stud-book du Cheval de Selle Luxembourgeois"),
(u"SDWA", u"Scottish Dutch Warmblood Association"),
(u"SF", u"Stud Book du Cheval Selle Français (ANSF)"),
(u"SHBGB", u"Sport Horse Breeding of Great Britain"),
(u"SLS", u"Studbook La Silla"),
(u"SSH", u"Scottish Sport Horse"),
(u"SSW", u"Studbook for Slovenian Warmblood Horses"),
(u"SWB", u"Swedish Warmblood Association"),
(u"TAF", u"Trakehner Avlsforbundet i Danmark"),
(u"THU", u"Verband der Thüringen Pferdezüchter"),
(u"TRAK", u"Verband der Züchter und Freunde des Ostpreussischen Warmblutpferdes Trakehner Abstammung e.V."),
(u"VNP", u"Verband Niederösterrichischer Pferdezüchter"),
(u"WESTF", u"Westfälisches Pferdestammbuch e.V."),
(u"WSI", u"Warmblood Studbook of Ireland"),
(u"ZANG", u"Stud-book Zangersheide"),
(u"ZCHKS", u"The Slovak Warmblood Studbook"),
(u"ZfDP", u"Zuchtverband für Deutsche Pferde e.v."),
(u"ZWEIB", u"Pferdezuchtverband Rheinland-Pfalz-Saar e.V."),
