matrix:
  include:
  - language: node_js
    install:
    - npm install grunt-cli grunt grunt-contrib-qunit
    script:
    - grunt test
  - language: python
    python: 2.6
    env: TOXENV=pytest29
  - language: python
    python: 2.6
    env: TOXENV=pytest30
  - language: python
    python: 2.7
    env: TOXENV=flake8
  - language: python
    python: 2.7
    env: TOXENV=pytest29
  - language: python
    python: 2.7
    env: TOXENV=pytest30
  - language: python
    python: 3.3
    env: TOXENV=pytest29
  - language: python
    python: 3.3
    env: TOXENV=pytest30
  - language: python
    python: 3.4
    env: TOXENV=pytest29
  - language: python
    python: 3.4
    env: TOXENV=pytest30
  - language: python
    python: 3.5
    env: TOXENV=flake8
  - language: python
    python: 3.5
    env: TOXENV=pytest29
  - language: python
    python: 3.5
    env: TOXENV=pytest30
  - language: python
    python: pypy
    env: TOXENV=pytest29
  - language: python
    python: pypy
    env: TOXENV=pytest30
  - language: python
    python: pypy3
    env: TOXENV=pytest29
  - language: python
    python: pypy3
    env: TOXENV=pytest30
  - language: python
    python: nightly
    env: TOXENV=pytest29
  - language: python
    python: nightly
    env: TOXENV=pytest30
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: davehunt
  password:
    secure: QTNaSfTEZnCEINpCfzdOiOPZ1s6co9Fz2cEt5zv/dSZAJCiKNZvvbMzsOsRMQl1MJvp+cSHiuOir46vEGxzh2+FIl+RRSlENqF2G7jGJpfJfukBxYAhSvt9ZLT4UyBbgYz5sv9A4zs+Yo72xAS9eP+zf5bDVaQh0EzudUbb0Mv4=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: pytest-dev/pytest-html
    python: 3.5
    condition: "$TOXENV = pytest30"
