---
# Kubernetes
cluster_name:   k8sdc
kubernetes_api_port: 6443
k8s_regen_certs:  false
k8s_regen_tokens: false
k8s_regen_users:  false
k8s_users:
  k8sdc:
    pass: password123
    role: admin
k8s_namespaces:
  - kube-system
  - k8sdc-infra
  - k8sdc-development
  - k8sdc-productivity
kubectl_http_proxy:  ''
kubectl_https_proxy: ''


# Docker
docker_registry_mirror_ip:    "{{ hostvars[groups['docker-registry-mirror'][0]]['ansible_' + interface].ipv4.address }}"
docker_registry_mirror_image: registry
docker_registry_mirror_tag:   2.4.1
docker_registry_mirror_http_proxy:  ''
docker_registry_mirror_https_proxy: ''
docker_insecure_registries:
  - "{{ docker_registry_mirror_ip }}"


# Fileserver
fileserver: "{{ groups['fileserver'][0] }}"
fileserver_http_proxy:  ''
fileserver_https_proxy: ''


# Solutions
solutions:
  cs1_cluster_services:
    enable:     yes
    namespace:  kube-system
    domain:     k8sdc.io
    cluster_ip: 10.254.1.1
    replicas:   1
    images:
      kubedns:
        image: gcr.io/google_containers/kubedns-amd64
        tag:   1.9
      dnsmasq:
        image: gcr.io/google_containers/kube-dnsmasq-amd64
        tag:   1.4
      healthz:
        image: gcr.io/google_containers/exechealthz-amd64
        tag:   v1.2.0
      heapster:
        image: gcr.io/google_containers/heapster
        tag:   v1.2.0

  cm1_cluster_management:
    enable:      yes
    namespace:   kube-system
    external_ip: "{{ hostvars[groups['k8sdc-nodes'][0]]['ansible_' + interface].ipv4.address }}"
    replicas:    1
    hostnames:
      - dashboard.k8sdc.io
    images:
      kube_dashboard:
        image: gcr.io/google_containers/kubernetes-dashboard-amd64
        tag:   v1.4.0

  dbs1_distributed_block_storage:
    enable:     yes
    namespace:  k8sdc-infra
    images:
      ceph:
        image: ceph/daemon
        tag:   tag-build-master-jewel-centos-7
    mon_hosts:
      - hostname: "{{ hostvars[groups['k8sdc-nodes'][0]]['ansible_fqdn'] }}"
      - hostname: "{{ hostvars[groups['k8sdc-nodes'][1]]['ansible_fqdn'] }}"
      - hostname: "{{ hostvars[groups['k8sdc-nodes'][2]]['ansible_fqdn'] }}"
    osd_hosts:
      - hostname:   "{{ hostvars[groups['k8sdc-nodes'][0]]['ansible_fqdn'] }}"
        count_256m: 60
      - hostname:   "{{ hostvars[groups['k8sdc-nodes'][1]]['ansible_fqdn'] }}"
        count_256m: 60
      - hostname:   "{{ hostvars[groups['k8sdc-nodes'][2]]['ansible_fqdn'] }}"
        count_256m: 60

  im1_identity_management:
    enable:    yes
    namespace: k8sdc-infra
    use_ceph:  yes
    replicas:  1
    hostnames: 
      - keycloak.k8sdc.io
    images:
      opendj:
        image:    k8sdc/opendj
        tag:      latest
        vol_size: 300
      keycloak:
        image:    jboss/keycloak
        tag:      1.9.3.Final
        vol_size: 1000

  hrp1_https_reverse_proxy:
    enable:     yes
    namespace:  k8sdc-infra
    images:
      traefik:
        image: traefik
        tag:   v1.0.3
    keepalived: 
      enable: no
      vip:    10.0.0.100

  m1_metrics:
    enable:    yes
    namespace: k8sdc-infra
    use_ceph:  yes
    replicas:  1
    hostnames:
      - prometheus.k8sdc.io
      - grafana.k8sdc.io
    images:
      prometheus:
        image:    prom/prometheus
        tag:      v1.3.1
        vol_size: 5000
      grafana:
        image:    grafana/grafana
        tag:      3.1.1-1470047149
        vol_size: 1000

  # l1_logging:
  #   enable:     yes
  #   namespace:  k8sdc-infra
  #   hostnames:
  #     kibana:         kibana.k8sdc.io
  #     kafka_admin:    kafka.k8sdc.io
  #     logstash_admin: logstash.k8sdc.io

  jm1_job_management:
    enable:    yes
    namespace: k8sdc-infra
    use_ceph:  yes
    replicas:  1
    hostnames:
      - jenkins.k8sdc.io
    images:
      jenkins:
        image:    jenkins
        tag:      2.7.4
        vol_size: 10000

  # as1_artifact_storage

  # ir1_image_repository

