# App settings go here, they're validated in app.main.load_settings
dev:
  py_file: app/main.py
  static_path: static/
# {% if database.is_none and example.is_message_board %}
message_file: 'messages.txt'
# {% elif database.is_postgres_sqlalchemy or database.is_postgres_raw %}
database:
  name: '{{ clean_name }}'
  user: 'postgres'  # TODO make sure connection settings here are correct
  password: 'You need to set this!'
  host: localhost
  port: 5432
# {% endif %}
# {% if session.is_secure %}
# this is the key used to encrypt cookies. Keep it safe!
# you can generate a new key with `base64.urlsafe_b64encode(os.urandom(32))`
cookie_secret_key: '{{ cookie_secret_key }}'
# {% endif %}
