# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[
                ('1', 'Cerulean'), ('2', 'Cosmo'), ('3', 'Cyborg'),
                ('4', 'Darkly'), ('5', 'Flatly'), ('6', 'Journal'),
                ('7', 'Lumen'), ('8', 'Paper'), ('9', 'Readable'),
                ('10', 'Sandstone'), ('11', 'Simplex'), ('12', 'Slate'),
                ('13', 'Spacelab'), ('14', 'Superhero'), ('15', 'United'),
                ('16', 'Yeti')
            ], default='1', max_length=2),
        ),
    ]
