url: https://pawelad.xyz/simple-site-crawler/
enforce_ssl: pawelad.xyz/simple-site-crawler/

theme: jekyll-theme-dinky

gems:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
