
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-01-19T12:12:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "81d09df9f6d836b9405afd6538c46a15375498ab",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
