---
- name: Check whether the swift service is enabled
  local_action: fail msg='Ceph-rgw-keystone is conflicted with swift, you should only enable one of them'
  when: enable_swift | bool

- name: Creating the Swift service and endpoint
  command: docker exec -t kolla_toolbox /usr/bin/ansible localhost
    -m kolla_keystone_service
    -a "service_name=swift
        service_type=object-store
        description='Openstack Object Storage'
        endpoint_region={{ openstack_region_name }}
        url='{{ item.url }}'
        interface='{{ item.interface }}'
        region_name={{ openstack_region_name }}
        auth={{ '{{ openstack_swift_auth }}' }}"
    -e "{'openstack_swift_auth':{{ openstack_swift_auth }}}"
  register: swift_endpoint
  changed_when: "{{ swift_endpoint.stdout.find('localhost | SUCCESS => ') != -1 and (swift_endpoint.stdout.split('localhost | SUCCESS => ')[1]|from_json).changed }}"
  until: swift_endpoint.stdout.split()[2] == 'SUCCESS'
  retries: 10
  delay: 5
  run_once: True
  with_items:
    - {'interface': 'admin', 'url': '{{ swift_admin_endpoint }}'}
    - {'interface': 'internal', 'url': '{{ swift_internal_endpoint }}'}
    - {'interface': 'public', 'url': '{{ swift_public_endpoint }}'}
