# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_openpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank_name',
            field=models.CharField(default='', max_length=30, verbose_name='Bank name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='brand',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('carnet', 'Carnet'), ('american express', 'American Express')], default='unknown', max_length=20, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefits',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='Benefits (as JSON)'),
        ),
    ]
