__version__ = "0.4.10"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.4.10)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '2e8b24716ce1bac50fff826afad02c048a5c589d'
__git_head_subject__ = 'Finished Release v0.4.10'
__git_head_message__ = ''
__git_dirty_diff__ = ''