sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3.3-5.2-alpha1
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-subunit
    - python: pypy
      env: TOXENV=pypy-subunit
install:
    - pip install tox-travis
script:
    - tox
notifications:
    email: false
