# coding=utf-8

MONGODB_URI_ENVIRONMENT_VARIABLE = 'MONSTRO_MONGODB_URI'
SETTINGS_ENVIRONMENT_VARIABLE = 'MONSTRO_SETTINGS'

TEST_DATABASE = '__monstro__'
TEST_MONGODB_URI = 'mongodb://localhost/' + TEST_DATABASE
