sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="https://github.com/django/django/tarball/master"

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO="Django>=1.4,<1.5"
  - python: "3.5"
    env: DJANGO="Django>=1.5,<1.6"
  - python: "3.5"
    env: DJANGO="Django>=1.6,<1.7"
  - python: "3.5"
    env: DJANGO="Django>=1.7,<1.8"

  - python: "3.4"
    env: DJANGO="Django>=1.4,<1.5"
  - python: "3.4"
    env: DJANGO="Django>=1.9,<1.10"
  - python: "3.4"
    env: DJANGO="Django>=1.10,<1.11"

  - python: "3.3"
    env: DJANGO="Django>=1.4,<1.5"
  - python: "3.3"
    env: DJANGO="Django>=1.9,<1.10"
  - python: "3.3"
    env: DJANGO="Django>=1.10,<1.11"
  - python: "3.3"
    env: DJANGO="https://github.com/django/django/tarball/master"

  - python: "3.2"
    env: DJANGO="Django>=1.4,<1.5"
  - python: "3.2"
    env: DJANGO="Django>=1.9,<1.10"
  - python: "3.2"
    env: DJANGO="Django>=1.10,<1.11"
  - python: "3.2"
    env: DJANGO="https://github.com/django/django/tarball/master"

  - python: "2.6"
    env: DJANGO="Django>=1.7,<1.8"
  - python: "2.6"
    env: DJANGO="Django>=1.8,<1.9"
  - python: "2.6"
    env: DJANGO="Django>=1.9,<1.10"
  - python: "2.6"
    env: DJANGO="Django>=1.10,<1.11"
  - python: "2.6"
    env: DJANGO="https://github.com/django/django/tarball/master"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/tarball/master"

before_install:
- pip install codecov

install:
  - pip install -q $DJANGO coverage==3.6

script:
  - coverage run --source=polymorphic runtests.py

after_success:
- codecov

branches:
  only:
    - master
