# Control file for Travis CI (http://travis-ci.org)
# Must be located in the root directory of the Git repository.

# By default, notification emails are sent to the PR creator and commiter.
notifications:
  email: false

#sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

# commands to install dependencies
install:
  - pip list
  - pip install --upgrade pip
  - make install
  - pip list
  - make develop
  - pip install python-coveralls
  - pip list
  - make clean

# commands to run builds & tests
script:
  - make check
  - make build
  - make builddoc
  - make test

after_success:
  - coveralls
