
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-01-16T13:26:24-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3a538ca9bb09376bbabdcf3549ed0b080e3a335",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
