# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openpay', '0008_auto_20161205_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='conciliated',
            field=models.BooleanField(default=True, verbose_name='Conciliated'),
        ),
    ]
