#Site Configuration
views:
    page:
        copyright:
         - '/copyright'
         - copyright
         - copyright.html
    posts:
        blog:
          - ['/','/page/<int:page>/']
          - postwall
          - index.html
    article:
        blog:
          - /article/<path:path>/
          - page
          - article.html
#    docs:
#        doc:
#         - /docs/<path:path>/
#         - page
#         - docs.html

    tags:
        blog:
          - ['/tag/<path:tag>/','/tag/<path:tag>/<int:page>/']
          - posts
          - index.html
    
Theme: default
Pagination: True