environment:
  matrix:

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "32"
      
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "64"
    
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
     
     
install:
    - "%PYTHON%\\python.exe -m pip install -r test-requirements.txt"
    - "git submodule update --init typeshed"
    - "%PYTHON%\\python.exe setup.py -q install"
   
build: off

test_script:
    # Ignore lint (it's run separately below), reports (since we don't have lxml),
    # and cmdline (since one of its tests depend on lxml)
    - "%PYTHON%\\python.exe runtests.py -x lint -x reports -x cmdline"
    - ps: if ($env:PYTHON_VERSION -Match "3.6.x" -And $env:PYTHON_ARCH -Match "64") { iex "$env:PYTHON\\python.exe -m flake8" }
