copyright: <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>

pages:
  - Home: index.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md

repo_name: 'GitHub'
repo_url: 'https://github.com/d0ugal/pynd'

site_author: Dougal Matthews
site_description: Search Python code.
site_dir: build/docs
site_name: Pynd
site_url: http://d0ugal.github.io/pynd/

theme: material

markdown_extensions:
    - toc:
        permalink: ¶
    - admonition:
    - codehilite(css_class=code):
    - footnotes:

google_analytics:
  - 'UA-89549313-1'
  - 'auto'

extra:
  version: !!python/object/apply:getattr
    - !!python/object/apply:__import__
      - 'pynd'
    - __version__
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'd0ugal'
    twitter: 'd0ugal'
