archive_older_than_days: 30
# path to sqlite database
engine: "sqlite:///:memory:"
influx:
  dbname: pv-nodes
  host: localhost
  password: no-need
  port: 8086
  user: no-need
tags:
  host: testhost.de
  region: europe
read_interval_seconds: 10
min_uptime_seconds_before_reboot: 900
log_level: DEBUG
checks:
  internet_connection:
    interval_seconds: 900 # 15 minutes
    min_fails_in_row: 2
  port_found:
    interval_seconds: 600 # 10 minutes
    min_fails_in_row: 3
  # optional, only implemented in sma rs485
  check_read_data:
    interval_seconds: 57600 # 16 hours
    min_fails_in_row: 10 # not really used, as never set to False

# specific for inverter type
# can be a list of kaco, sma_rs485, sbfspot
inverter_type:
  - "kaco"
  - "sbfspot"
kaco_port: "/dev/ttyUSB*"
kaco_inverter_ids: [1,2,3]

# specific for sma_rs485
sma_rs485_max_devices: 9

# specific for sbfspot
sbfspot_sqlite_file: "/tmp/example/path-to-db.sqlite"
