# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 09:09
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20161121_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=filebrowser.fields.FileBrowseField(max_length=255, verbose_name='image'),
        ),
    ]
