# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-20 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codebehind', '0003_auto_20160620_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersecret',
            name='verification_code',
        ),
    ]
