# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=200, verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('portfolio_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.PortfolioPost')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
