
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-01-08T21:08:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c2c19a3014bfb5f0d6b95bbbf9c8f9caadb17366",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
