
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-12-27T16:41:33-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "86ac5c19e8d913d3ca1932fddd67d28e2f46922b",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
