language: python
sudo: false
python:
    - pypy
    - pypy3
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install zc.buildout
    - buildout
script:
    - bin/test -v1j99
notifications:
    email: false
cache:
  directories:
    - eggs
