sudo: false
language: python
python:
- 2.7
- 3.6
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.6
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: iE+AgX9PCRJrCmmBpAQNpLfZH4KmCQPxqJnHjZS7xLtwL81XqeJuziX+XN0O6JziKXME7PJJplSLCVkdfQfqHVZz5u5ZTrsTCX36bgeD6UYIh5epa0wl+FZvL2EXyFB3vhNzgsp17gXNSWGZWB3Mq4MWzWq4J0y4IvyedjpWPvnTEkBBDsABuBDKKxPak/wQik5dLMY1unavAUTvaxaLFiuAE5GCh8sysCp/0yCmsk2onM/6j2nafa3RGfT2zrfZNyUGxDT5IAOLjnA86Xghinl9KwQndx3z+p3Czs5CZzmFEouEbcZss6Q2NzUBTd9Md7qC6Ct0K38OdEdBH4sNomheM/B54CF1S2vK6CmyAElKKNc3wYZgEnjmzvQ3wubx336SE9FBvFt3qCLsQuXGq/Xh+9DJ3BnjiIyXJOgDlt2ogaJbgaAfQOVW4JLxnYj7b3W8khAAtpAmzEHinY86Fzq0d61rWJUfyMwROEhCY6FuPJk0+8qMG0UhtpXhgCukmO9RWJ6LAItAn/gb0bEPEwxYnIaplvoppLu8EXqeAMVyEcne4oBrKjW+EJMO91mr96U57GMUQ7bB/S6CiJiSeJLOqFeY4cPkpwWtcTvdzUiwTKtRrRzTzw1sAdRAkRZ65d+VZdIhj8wkIvQDpelGDx9fAdkp0E0cU9rOG0K5G9M=
