---
- name: Pulling karbor-api image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ karbor_api_image_full }}"
  when: inventory_hostname in groups['karbor-api']

- name: Pulling karbor-protection image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ karbor_protection_image_full }}"
  when: inventory_hostname in groups['karbor-protection']

- name: Pulling karbor-operationengine image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ karbor_operationengine_image_full }}"
  when: inventory_hostname in groups['karbor-operationengine']
