
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e34c9a580538a9a14fec9b4bbab8b8df92ad36e7",
 "version": "0.3.post17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
