language: python

addons:
  firefox: "45.0"

services:
  - postgresql
  - redis-server

matrix:
    include:
        - python: 3.5
          env:
          - PYTHON_VERSION=python3.5
          - TOXENV=py35

# http://stackoverflow.com/a/19460794/315168
cache:
  directories:
    # /home/travis/.cache/pip/wheels is the normal pip cache folder
    - $HOME/.cache/pip
    - .tox

install:
  - travis_retry pip install tox

# http://stackoverflow.com/questions/39279651/connection-refused-when-running-selenium-tests-in-marionette
#  - npm install -g geckodriver

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
  - pip install -U pip
  - pip install -e .[test]

script:
  - pip freeze
  - py.test tests --ini=pyramid_notebook/demo/development.ini



