# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer', verbose_name='customer'),
            preserve_default=False,
        ),
    ]
