# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20161230_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ('pk',), 'verbose_name': 'cart product', 'verbose_name_plural': 'cart products'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('pk',), 'verbose_name': 'order product', 'verbose_name_plural': 'order products'},
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product', verbose_name='product'),
        ),
    ]
