# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20161230_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbillingdata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_data', to='shop.Order'),
        ),
        migrations.AlterField(
            model_name='ordershippingdata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_data', to='shop.Order'),
        ),
    ]
