# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170105_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_subcategories', to='shop.Category', verbose_name='parent'),
        ),
    ]
