# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2016-12-22 18:29:07.872017
from __future__ import unicode_literals
import datetime

version = "1.0.7"
githash = "a983582e099dc66966a1699ebdaeec62848df60b"


major = 1
minor = 0
bugfix = 7

release = True
timestamp = datetime.datetime(2016, 12, 22, 18, 29, 7, 872017)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
