# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.codeEditor = QtWidgets.QTextEdit(self.centralwidget)
        self.codeEditor.setGeometry(QtCore.QRect(20, 10, 461, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.codeEditor.sizePolicy().hasHeightForWidth())
        self.codeEditor.setSizePolicy(sizePolicy)
        self.codeEditor.setObjectName("codeEditor")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(500, 10, 134, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = Regname(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.val_d = Numlabel(self.layoutWidget)
        self.val_d.setText("")
        self.val_d.setAlignment(QtCore.Qt.AlignCenter)
        self.val_d.setObjectName("val_d")
        self.gridLayout.addWidget(self.val_d, 2, 3, 1, 1)
        self.val_h = Numlabel(self.layoutWidget)
        self.val_h.setStyleSheet("alignment: central;")
        self.val_h.setText("")
        self.val_h.setAlignment(QtCore.Qt.AlignCenter)
        self.val_h.setObjectName("val_h")
        self.gridLayout.addWidget(self.val_h, 4, 1, 1, 1)
        self.label_6 = Regname(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5 = Regname(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3 = Regname(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.val_c = Numlabel(self.layoutWidget)
        self.val_c.setText("")
        self.val_c.setAlignment(QtCore.Qt.AlignCenter)
        self.val_c.setObjectName("val_c")
        self.gridLayout.addWidget(self.val_c, 2, 2, 1, 1)
        self.val_a = Numlabel(self.layoutWidget)
        self.val_a.setText("")
        self.val_a.setAlignment(QtCore.Qt.AlignCenter)
        self.val_a.setObjectName("val_a")
        self.gridLayout.addWidget(self.val_a, 2, 0, 1, 1)
        self.label_4 = Regname(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.val_l = Numlabel(self.layoutWidget)
        self.val_l.setText("")
        self.val_l.setAlignment(QtCore.Qt.AlignCenter)
        self.val_l.setObjectName("val_l")
        self.gridLayout.addWidget(self.val_l, 4, 2, 1, 1)
        self.val_e = Numlabel(self.layoutWidget)
        self.val_e.setObjectName("val_e")
        self.gridLayout.addWidget(self.val_e, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.val_b = Numlabel(self.layoutWidget)
        self.val_b.setText("")
        self.val_b.setAlignment(QtCore.Qt.AlignCenter)
        self.val_b.setObjectName("val_b")
        self.gridLayout.addWidget(self.val_b, 2, 1, 1, 1)
        self.label = Regname(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2 = Regname(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 4)
        self.gridLayout.setColumnMinimumWidth(0, 28)
        self.gridLayout.setColumnMinimumWidth(1, 28)
        self.gridLayout.setColumnMinimumWidth(2, 28)
        self.gridLayout.setColumnMinimumWidth(3, 28)
        self.gridLayout.setRowMinimumHeight(0, 15)
        self.gridLayout.setRowMinimumHeight(1, 15)
        self.gridLayout.setRowMinimumHeight(2, 15)
        self.gridLayout.setRowMinimumHeight(3, 15)
        self.gridLayout.setRowMinimumHeight(4, 15)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = Regname(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.val_s = Numlabel(self.layoutWidget)
        self.val_s.setText("")
        self.val_s.setObjectName("val_s")
        self.gridLayout_2.addWidget(self.val_s, 2, 0, 1, 1)
        self.val_z = Numlabel(self.layoutWidget)
        self.val_z.setText("")
        self.val_z.setObjectName("val_z")
        self.gridLayout_2.addWidget(self.val_z, 2, 1, 1, 1)
        self.label_10 = Regname(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_13 = Regname(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 4, 1, 1)
        self.label_11 = Regname(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_12 = Regname(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 3, 1, 1)
        self.val_p = Numlabel(self.layoutWidget)
        self.val_p.setText("")
        self.val_p.setObjectName("val_p")
        self.gridLayout_2.addWidget(self.val_p, 2, 3, 1, 1)
        self.val_ac = Numlabel(self.layoutWidget)
        self.val_ac.setText("")
        self.val_ac.setObjectName("val_ac")
        self.gridLayout_2.addWidget(self.val_ac, 2, 2, 1, 1)
        self.val_cy = Numlabel(self.layoutWidget)
        self.val_cy.setText("")
        self.val_cy.setObjectName("val_cy")
        self.gridLayout_2.addWidget(self.val_cy, 2, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 5)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = Regname(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.val_pc = Numlabel(self.layoutWidget)
        self.val_pc.setText("")
        self.val_pc.setObjectName("val_pc")
        self.gridLayout_3.addWidget(self.val_pc, 0, 1, 1, 1)
        self.label_16 = Regname(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.val_sp = Numlabel(self.layoutWidget)
        self.val_sp.setText("")
        self.val_sp.setObjectName("val_sp")
        self.gridLayout_3.addWidget(self.val_sp, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 220, 461, 192))
        self.tableView.setShowGrid(False)
        self.tableView.setGridStyle(QtCore.Qt.NoPen)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(25)
        self.tableView.horizontalHeader().setMinimumSectionSize(25)
        self.tableView.verticalHeader().setDefaultSectionSize(19)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCompile = QtWidgets.QAction(MainWindow)
        self.actionCompile.setObjectName("actionCompile")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionExecute = QtWidgets.QAction(MainWindow)
        self.actionExecute.setObjectName("actionExecute")
        self.menu.addAction(self.actionCompile)
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.actionExecute)
        self.menubar.addAction(self.menu.menuAction())
        self.label_14.setBuddy(self.label_14)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "L"))
        self.label_6.setText(_translate("MainWindow", "H"))
        self.label_5.setText(_translate("MainWindow", "E"))
        self.label_3.setText(_translate("MainWindow", "C"))
        self.label_4.setText(_translate("MainWindow", "D"))
        self.val_e.setText(_translate("MainWindow", "FF"))
        self.label.setText(_translate("MainWindow", "A"))
        self.label_2.setText(_translate("MainWindow", "B"))
        self.label_8.setText(_translate("MainWindow", "Регистры"))
        self.label_9.setText(_translate("MainWindow", "S"))
        self.label_10.setText(_translate("MainWindow", "Z"))
        self.label_13.setText(_translate("MainWindow", "CY"))
        self.label_11.setText(_translate("MainWindow", "AC"))
        self.label_12.setText(_translate("MainWindow", "P"))
        self.label_15.setText(_translate("MainWindow", "Флаги"))
        self.label_14.setText(_translate("MainWindow", "PC:"))
        self.label_16.setText(_translate("MainWindow", "SP:"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.actionCompile.setText(_translate("MainWindow", "Скомпилировать"))
        self.action.setText(_translate("MainWindow", "Открыть"))
        self.action_2.setText(_translate("MainWindow", "Сохранить"))
        self.actionExecute.setText(_translate("MainWindow", "Выполнить"))

from .numlabel import Numlabel
from .regname import Regname
